type Post = {
  "id": number,
  "sticky": boolean,
  "title": string,
  "name": string,
  "image": string,
  "tag1": string,
  "tag2": string,
  "date": string,
}

type Destination = {
  "id": number,
  "rank": number,
  "city": string,
  "country": string,
  "image": string,
  "featured": boolean,
  "continent": string,
  "mood": string[],
}

type Country = {
  "id": number,
  "name": string,
  "image": string,
  "featured": boolean,
  "continent": string,
  "mood": string[],
  "rank": number,
  "vacationgoal"?: string[],
  "safe"?: boolean,
  "fastInternet"?: boolean,
  "cleanAir"?: boolean,
  "hiddenGem"?: boolean,
  "popular"?: boolean,
  "familyFriendly"?: boolean,
  "amazingFood"?: boolean,
  "nightlife"?: boolean,
  "greatForDating"?: boolean,
  "ecofriendly"?: boolean,
  "dogfriendly"?: boolean,
  "lgbtqfriendly"?: boolean,
  "lowRacism"?: boolean,
  "muslimfriendly"?: boolean,
  "created_at"?: string,
  "updated_at"?: string,
}

type City = {
  "id": number,
  "name": string,
  "country": number,
  "image": string,
  "featured": boolean,
  "rank"?: number,
  "mood": string[],
  "description"?: string,
  "created_at"?: string,
  "updated_at"?: string,
}